defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: true
controller:
  manager:
    clientCache:
      persistenceModel: direct-encrypted
      storageEncryption:
        enabled: true
        mount: auth-mount
        keyName: vso-client-cache
        transitMount: transit
        kubernetes:
          role: auth-role-operator
          serviceAccount: vault-secrets-operator-controller-manager
          tokenAudiences: ["vault"]
enableMonitoring: false
enableCertManager: true
env:
  - name: VAULT_ADDR
    value: https://vault.vault:8200
  - name: VAULT_CACERT
    value: /vault-certs/vault.ca
volumes:
  - name: vault-certs
    secret:
      secretName: vault-certs
volumeMounts:
  - mountPath: /vault-certs
    name: vault-certs
