apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: kv
spec:
  authentication:
    path: kubernetes
    role: config-admin
  type: kv
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: kv-system
spec:
  authentication:
    path: kubernetes
    role: config-admin
  type: kv
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: test
spec:
  authentication:
    path: kubernetes-test
    role: vault
  type: kv
