apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{- if .Values.enableCertManager }}{{- printf "%s/vault-config-operator-webhook-service-cert" .Release.Namespace }}{{- end }}'
    service.beta.openshift.io/inject-cabundle: '{{- if .Values.enableCertManager }} {{- printf "false" }} {{- else }} {{- printf "true" }} {{- end }}'
  creationTimestamp: null
  name: vault-config-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-authenginemount
  failurePolicy: Fail
  name: vauthenginemount.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - authenginemounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-azureauthengineconfig
  failurePolicy: Fail
  name: vazureauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - azureauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-azureauthenginerole
  failurePolicy: Fail
  name: vazureauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - azureauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-azuresecretengineconfig
  failurePolicy: Fail
  name: vazuresecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuresecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-databasesecretengineconfig
  failurePolicy: Fail
  name: vdatabasesecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databasesecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-databasesecretenginerole
  failurePolicy: Fail
  name: vdatabasesecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - databasesecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-databasesecretenginestaticrole
  failurePolicy: Fail
  name: vdatabasesecretenginestaticrole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databasesecretenginestaticroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-gcpauthengineconfig
  failurePolicy: Fail
  name: vgcpauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - gcpauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-gcpauthenginerole
  failurePolicy: Fail
  name: vgcpauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - gcpauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-githubsecretengineconfig
  failurePolicy: Fail
  name: vgithubsecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - githubsecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-githubsecretenginerole
  failurePolicy: Fail
  name: vgithubsecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - githubsecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-group
  failurePolicy: Fail
  name: vgroup.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-groupalias
  failurePolicy: Fail
  name: vgroupalias.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groupalias
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-jwtoidcauthengineconfig
  failurePolicy: Fail
  name: vjwtoidcauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - jwtoidcauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-jwtoidcauthenginerole
  failurePolicy: Fail
  name: vjwtoidcauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - jwtoidcauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-kubernetesauthengineconfig
  failurePolicy: Fail
  name: vkubernetesauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - kubernetesauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-kubernetesauthenginerole
  failurePolicy: Fail
  name: vkubernetesauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubernetesauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-kubernetessecretengineconfig
  failurePolicy: Fail
  name: vkubernetessecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - kubernetessecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-kubernetessecretenginerole
  failurePolicy: Fail
  name: vkubernetessecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - kubernetessecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-ldapauthengineconfig
  failurePolicy: Fail
  name: vldapauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - ldapauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-ldapauthenginegroup
  failurePolicy: Fail
  name: vldapauthenginegroup.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - ldapauthenginegroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-pkisecretengineconfig
  failurePolicy: Fail
  name: vpkisecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - pkisecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-pkisecretenginerole
  failurePolicy: Fail
  name: vpkisecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - pkisecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-quaysecretengineconfig
  failurePolicy: Fail
  name: vquaysecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - quaysecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-quaysecretenginerole
  failurePolicy: Fail
  name: vquaysecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - quaysecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-quaysecretenginestaticrole
  failurePolicy: Fail
  name: vquaysecretenginestaticrole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - quaysecretenginestaticroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-rabbitmqsecretenginerole
  failurePolicy: Fail
  name: vrabbitmqsecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - rabbitmqsecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-randomsecret
  failurePolicy: Fail
  name: vrandomsecret.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - randomsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-secretenginemount
  failurePolicy: Fail
  name: vsecretenginemount.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - secretenginemounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /validate-redhatcop-redhat-io-v1alpha1-vaultsecret
  failurePolicy: Fail
  name: vvaultsecret.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vaultsecrets
  sideEffects: None
