apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{- if .Values.enableCertManager }}{{- printf "%s/vault-config-operator-webhook-service-cert" .Release.Namespace }}{{- end }}'
    service.beta.openshift.io/inject-cabundle: '{{- if .Values.enableCertManager }} {{- printf "false" }} {{- else }} {{- printf "true" }} {{- end }}'
  creationTimestamp: null
  name: vault-config-operator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-authenginemount
  failurePolicy: Fail
  name: mauthenginemount.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - authenginemounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-azureauthengineconfig
  failurePolicy: Fail
  name: mazureauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - azureauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-azureauthenginerole
  failurePolicy: Fail
  name: mazureauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - azureauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-azuresecretengineconfig
  failurePolicy: Fail
  name: mazuresecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - azuresecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-databasesecretengineconfig
  failurePolicy: Fail
  name: mdatabasesecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - databasesecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-databasesecretenginerole
  failurePolicy: Fail
  name: mdatabasesecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - databasesecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-databasesecretenginestaticrole
  failurePolicy: Fail
  name: mdatabasesecretenginestaticrole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - databasesecretenginestaticroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-gcpauthengineconfig
  failurePolicy: Fail
  name: mgcpauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - gcpauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-gcpauthenginerole
  failurePolicy: Fail
  name: mgcpauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - gcpauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-githubsecretengineconfig
  failurePolicy: Fail
  name: mgithubsecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - githubsecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-githubsecretenginerole
  failurePolicy: Fail
  name: mgithubsecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - githubsecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-group
  failurePolicy: Fail
  name: mgroup.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-groupalias
  failurePolicy: Fail
  name: mgroupalias.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groupalias
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-jwtoidcauthengineconfig
  failurePolicy: Fail
  name: mjwtoidcauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - jwtoidcauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-jwtoidcauthenginerole
  failurePolicy: Fail
  name: mjwtoidcauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - jwtoidcauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-kubernetesauthengineconfig
  failurePolicy: Fail
  name: mkubernetesauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - kubernetesauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-kubernetesauthenginerole
  failurePolicy: Fail
  name: mkubernetesauthenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - kubernetesauthengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-kubernetessecretengineconfig
  failurePolicy: Fail
  name: mkubernetessecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - kubernetessecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-kubernetessecretenginerole
  failurePolicy: Fail
  name: mkubernetessecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - kubernetessecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-ldapauthengineconfig
  failurePolicy: Fail
  name: mldapauthengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - ldapauthengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-ldapauthenginegroup
  failurePolicy: Fail
  name: mldapauthenginegroup.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - ldapauthenginegroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-passwordpolicy
  failurePolicy: Fail
  name: mpasswordpolicy.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - passwordpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-pkisecretengineconfig
  failurePolicy: Fail
  name: mpkisecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - pkisecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-pkisecretenginerole
  failurePolicy: Fail
  name: mpkisecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - pkisecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-policy
  failurePolicy: Fail
  name: mpolicy.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - policies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-quaysecretengineconfig
  failurePolicy: Fail
  name: mquaysecretengineconfig.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - quaysecretengineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-quaysecretenginerole
  failurePolicy: Fail
  name: mquaysecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - quaysecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-quaysecretenginestaticrole
  failurePolicy: Fail
  name: mquaysecretenginestaticrole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - quaysecretenginestaticroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-rabbitmqsecretenginerole
  failurePolicy: Fail
  name: mrabbitmqsecretenginerole.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - rabbitmqsecretengineroles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-randomsecret
  failurePolicy: Fail
  name: mrandomsecret.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - randomsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-secretenginemount
  failurePolicy: Fail
  name: msecretenginemount.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - secretenginemounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: vault-config-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-redhatcop-redhat-io-v1alpha1-vaultsecret
  failurePolicy: Fail
  name: mvaultsecret.kb.io
  rules:
  - apiGroups:
    - redhatcop.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vaultsecrets
  sideEffects: None
