apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-config-operator.fullname" . }}
  labels:
    {{- include "vault-config-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vault-config-operator.selectorLabels" . | nindent 6 }}
      control-plane: vault-config-operator
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "vault-config-operator.selectorLabels" . | nindent 8 }}
        control-plane: vault-config-operator
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: controller-manager
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      {{- if .Values.enableMonitoring }}
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --tls-cert-file=/etc/certs/tls/tls.crt
        - --tls-private-key-file=/etc/certs/tls/tls.key
        - --v=0
        image: "{{ .Values.kube_rbac_proxy.image.repository }}:{{ .Values.kube_rbac_proxy.image.tag }}"
        name: kube-rbac-proxy
        securityContext:
          {{- toYaml .Values.kube_rbac_proxy.securityContext | nindent 10 }}
        ports:
        - containerPort: 8443
          name: https
        volumeMounts:
        - mountPath: /etc/certs/tls
          name: metrics-service-cert
        imagePullPolicy: {{ .Values.kube_rbac_proxy.image.pullPolicy }}
        resources:
          {{- toYaml .Values.kube_rbac_proxy.resources | nindent 10 }}
      {{- end }}
      - command:
        - /manager
        args:
        - --leader-elect
        {{- with .Values.args }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: webhook-service-cert
          readOnly: true
          mountPath: /tmp/k8s-webhook-server/serving-certs
        {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.enableMonitoring }}
      - name: metrics-service-cert
        secret:
          defaultMode: 420
          {{- if .Values.enableCertManager }}
          secretName: vault-config-operator-metrics-service-cert
          {{- else }}
          secretName: vault-config-operator-certs
          {{- end }}
      {{- end }}
      - name: webhook-service-cert
        secret:
          {{- if .Values.enableCertManager }}
          secretName: vault-config-operator-webhook-service-cert
          {{- else }}
          secretName: webhook-server-cert
          {{- end }}
          defaultMode: 420
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
