apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: webhook-server-cert
  name: vault-config-operator-webhook-service
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: vault-config-operator
