apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: vault-config-operator-certs
  labels:
    control-plane: vault-config-operator
  name: vault-config-operator-controller-manager-metrics-service
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: vault-config-operator
