apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vault.mgmtv2.cedille.club
  dnsNames:
    - vault.mgmtv2.cedille.club
  # Optional: Set the duration and renewal time
  duration: 2160h
  renewBefore: 360h
